# Generated by Django 5.0.6 on 2024-06-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="img",
            field=models.ImageField(default="", upload_to="core/images"),
        ),
    ]
